name: tf-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - jupyter
  - notebook
  - ipykernel
  - ipywidgets
  - seaborn
  - tensorflow
  - beautifulsoup4
  - requests
  - jinja2
  - pytz
  - packaging
  - traitlets
  - psutil
  - pyyaml
  - typing-extensions
  - tqdm
  - pip:
      - anyio==4.6.2
